export type CustomersType = {
  user_id?: number
  id?: number
  template: string
  fio: string
  first_name: string
  last_name: string
  pat_name: string
  phone: string
  sms_verify: boolean
  email: string
  birthday: string
  gender: string
  car_number: string
  discount: string
  bonus: string
  bonus_last: string
  write_off_last: string
  loyalty_level: string
  summ: string
  summ_all: string
  summ_last: string
  visits: string
  visits_all: string
  date_last: string
  barcode: string
  key1: string
  key2: string
  key3: string
  key4: string
  key5: string
  key6: string
  trg_action_type: string
  trg_action_value: string
  trg_date_type: string
  trg_date_value: string
  delivery_form: string
  o_s: string
  link: string
  referal: string
  backgroundColor: string
  created_at: string
  H1: any
  H2: any
  H3: any
  S1: any
  S2: any
  S3: any
  B1: any
  B2: string
  B3: any
  B4: any
  B5: any
  B6: any
}
